# Настройки автоматического применения шаблона
defaults:
  - scope:
      path: "" # Применять ко всем файлам в репозитории
    values:
      layout: "default" # Имя вашего шаблона из папки _layouts

# Правильные ссылки (чтобы страницы открывались по названию, например /coils.html)
permalink: /:basename.html
