# Полностью отключаем сторонние темы, чтобы работал наш default.html
theme: ""

# Заставляем Гитхаб принудительно читать наш кастомный шаблон
permalink: /:basename.html
markdown: kramdown
encoding: "utf-8"
