# =============================================================
# СИСТЕМНАЯ КОНФИГУРАЦИЯ МЕЖДУНАРОДНОЙ ВИКИПЕДИИ A51BFCTS
# =============================================================

title: Вики a51bfcts
description: Area 51 but find coils to survive — Энциклопедия предметов и гайдов
remote_theme: pages-themes/cayman@v0.2.0

# Включаем встроенные плагины Гитхаба для правильной обработки Markdown
plugins:
  - jekyll-remote-theme

# Заставляем сервер внедрять CSS-файл в шапку всех страниц
header_pages:
  - style.css

# Настройки кодировки для защиты от иероглифов
encoding: "utf-8"
markdown: kramdown
