name: Deploy Rust mdBook
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v4

      # ОФИЦИАЛЬНЫЙ СБОРЩИК MDBOOK
      - name: Установка и настройка mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Чистая сборка книги через Rust
        run: mdbook build

      # ПУБЛИКАЦИЯ С ОБНОВЛЕННОЙ ВЕРСИЕЙ ДО V4
      - name: Публикация на GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
